spring.application.name=portal

# Database Connection Settings
spring.datasource.url=jdbc:postgresql://ep-broad-band-aorv3rt7-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_huJjPbXNi04L
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate/JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Thymeleaf Cache (Turn off so UI updates instantly on refresh)
spring.thymeleaf.cache=false